const datas = [
  {
    L_ID: 12565,
    L_PARID: -1,
    C_ZQCODE: '200000',
    C_ZQNAME: '全国',
    child: [
      {
        L_ID: 12566,
        L_PARID: 12565,
        C_ZQCODE: '11',
        C_ZQNAME: '北京市',
        child: [
          {
            L_ID: 12567,
            L_PARID: 12566,
            C_ZQCODE: '1101',
            C_ZQNAME: '市辖区',
            isLeaf: false,
            child: [
              {
                L_ID: 12568,
                L_PARID: 12567,
                C_ZQCODE: '110101',
                C_ZQNAME: '东城区',
                isLeaf: false,
              },
              {
                L_ID: 12586,
                L_PARID: 12567,
                C_ZQCODE: '110102',
                C_ZQNAME: '西城区',
                isLeaf: false,
              },
              {
                L_ID: 12602,
                L_PARID: 12567,
                C_ZQCODE: '110105',
                C_ZQNAME: '朝阳区',
                isLeaf: false,
              },
              {
                L_ID: 12645,
                L_PARID: 12567,
                C_ZQCODE: '110106',
                C_ZQNAME: '丰台区',
                isLeaf: false,
              },
              {
                L_ID: 12652,
                L_PARID: 12567,
                C_ZQCODE: '110107',
                C_ZQNAME: '石景山区',
                isLeaf: false,
              },
              {
                L_ID: 12662,
                L_PARID: 12567,
                C_ZQCODE: '110108',
                C_ZQNAME: '海淀区',
                isLeaf: false,
              },
              {
                L_ID: 12673,
                L_PARID: 12567,
                C_ZQCODE: '110109',
                C_ZQNAME: '门头沟区',
                isLeaf: false,
              },
              {
                L_ID: 12689,
                L_PARID: 12567,
                C_ZQCODE: '110111',
                C_ZQNAME: '房山区',
                isLeaf: false,
              },
              {
                L_ID: 12719,
                L_PARID: 12567,
                C_ZQCODE: '110112',
                C_ZQNAME: '通州区',
                isLeaf: false,
              },
              {
                L_ID: 12736,
                L_PARID: 12567,
                C_ZQCODE: '110113',
                C_ZQNAME: '顺义区',
                isLeaf: false,
              },
              {
                L_ID: 12757,
                L_PARID: 12567,
                C_ZQCODE: '110114',
                C_ZQNAME: '昌平区',
                isLeaf: false,
              },
              {
                L_ID: 12778,
                L_PARID: 12567,
                C_ZQCODE: '110115',
                C_ZQNAME: '大兴区',
                isLeaf: false,
              },
              {
                L_ID: 12796,
                L_PARID: 12567,
                C_ZQCODE: '110116',
                C_ZQNAME: '怀柔区',
                isLeaf: false,
              },
              {
                L_ID: 12812,
                L_PARID: 12567,
                C_ZQCODE: '110117',
                C_ZQNAME: '平谷区',
                isLeaf: false,
              },
              {
                L_ID: 12833,
                L_PARID: 12567,
                C_ZQCODE: '110128',
                C_ZQNAME: '密云县',
                isLeaf: false,
                child: [
                  {
                    L_ID: 12834,
                    L_PARID: 12833,
                    C_ZQCODE: '110128001',
                    C_ZQNAME: '石城',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12835,
                    L_PARID: 12833,
                    C_ZQCODE: '110128002',
                    C_ZQNAME: '冯家峪',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12836,
                    L_PARID: 12833,
                    C_ZQCODE: '110128003',
                    C_ZQNAME: '不老屯',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12837,
                    L_PARID: 12833,
                    C_ZQCODE: '110128004',
                    C_ZQNAME: '高岭',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12838,
                    L_PARID: 12833,
                    C_ZQCODE: '110128005',
                    C_ZQNAME: '古北口',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12839,
                    L_PARID: 12833,
                    C_ZQCODE: '110128006',
                    C_ZQNAME: '太师屯',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12840,
                    L_PARID: 12833,
                    C_ZQCODE: '110128007',
                    C_ZQNAME: '新城子',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12841,
                    L_PARID: 12833,
                    C_ZQCODE: '110128008',
                    C_ZQNAME: '西田各庄',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12842,
                    L_PARID: 12833,
                    C_ZQCODE: '110128009',
                    C_ZQNAME: '溪翁庄',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12843,
                    L_PARID: 12833,
                    C_ZQCODE: '110128010',
                    C_ZQNAME: '北庄',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12844,
                    L_PARID: 12833,
                    C_ZQCODE: '110128011',
                    C_ZQNAME: '十里堡',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12845,
                    L_PARID: 12833,
                    C_ZQCODE: '110128012',
                    C_ZQNAME: '密云镇',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12846,
                    L_PARID: 12833,
                    C_ZQCODE: '110128013',
                    C_ZQNAME: '檀营',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12847,
                    L_PARID: 12833,
                    C_ZQCODE: '110128014',
                    C_ZQNAME: '穆家峪',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12848,
                    L_PARID: 12833,
                    C_ZQCODE: '110128015',
                    C_ZQNAME: '大城子',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12849,
                    L_PARID: 12833,
                    C_ZQCODE: '110128016',
                    C_ZQNAME: '巨各庄',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12850,
                    L_PARID: 12833,
                    C_ZQCODE: '110128017',
                    C_ZQNAME: '河南寨',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12851,
                    L_PARID: 12833,
                    C_ZQCODE: '110128018',
                    C_ZQNAME: '东邵渠',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12852,
                    L_PARID: 12833,
                    C_ZQCODE: '110128019',
                    C_ZQNAME: '云蒙山林场',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12853,
                    L_PARID: 12833,
                    C_ZQCODE: '110128020',
                    C_ZQNAME: '雾灵山林场',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12854,
                    L_PARID: 12833,
                    C_ZQCODE: '110128021',
                    C_ZQNAME: '五座楼林场',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12855,
                    L_PARID: 12833,
                    C_ZQCODE: '110128022',
                    C_ZQNAME: '水库林场',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12856,
                    L_PARID: 12833,
                    C_ZQCODE: '110128023',
                    C_ZQNAME: '白龙潭',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12857,
                    L_PARID: 12833,
                    C_ZQCODE: '110128024',
                    C_ZQNAME: '锥峰山林场',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12858,
                    L_PARID: 12833,
                    C_ZQCODE: '110128025',
                    C_ZQNAME: '潮白河林场',
                    isLeaf: true,
                  },
                  {
                    L_ID: 12859,
                    L_PARID: 12833,
                    C_ZQCODE: '110128026',
                    C_ZQNAME: '荆子峪苗圃',
                    isLeaf: true,
                  },
                ],
              },
              {
                L_ID: 12860,
                L_PARID: 12567,
                C_ZQCODE: '110129',
                C_ZQNAME: '延庆县',
                isLeaf: false,
              },
            ],
          },
        ],
      },
      {
        L_ID: 50548,
        L_PARID: 12565,
        C_ZQCODE: '12',
        C_ZQNAME: '天津市',
      },
      {
        L_ID: 12878,
        L_PARID: 12565,
        C_ZQCODE: '13',
        C_ZQNAME: '河北省',
      },
      {
        L_ID: 15525,
        L_PARID: 12565,
        C_ZQCODE: '14',
        C_ZQNAME: '山西省',
      },
      {
        L_ID: 61459,
        L_PARID: 12565,
        C_ZQCODE: '15',
        C_ZQNAME: '内蒙古自治区',
      },
      {
        L_ID: 16977,
        L_PARID: 12565,
        C_ZQCODE: '21',
        C_ZQNAME: '辽宁省',
      },
      {
        L_ID: 59911,
        L_PARID: 12565,
        C_ZQCODE: '22',
        C_ZQNAME: '吉林省',
      },
      {
        L_ID: 18303,
        L_PARID: 12565,
        C_ZQCODE: '23',
        C_ZQNAME: '黑龙江省',
      },
      {
        L_ID: 19767,
        L_PARID: 12565,
        C_ZQCODE: '31',
        C_ZQNAME: '上海市',
      },
      {
        L_ID: 20020,
        L_PARID: 12565,
        C_ZQCODE: '32',
        C_ZQNAME: '江苏省',
      },
      {
        L_ID: 21528,
        L_PARID: 12565,
        C_ZQCODE: '33',
        C_ZQNAME: '浙江省',
      },
      {
        L_ID: 23233,
        L_PARID: 12565,
        C_ZQCODE: '34',
        C_ZQNAME: '安徽省',
      },
      {
        L_ID: 25097,
        L_PARID: 12565,
        C_ZQCODE: '35',
        C_ZQNAME: '福建省',
        child: [
          {
            L_ID: 25098,
            L_PARID: 25097,
            C_ZQCODE: '3501',
            C_ZQNAME: '福州市',
            isLeaf: false,
            child: [
              {
                L_ID: 25099,
                L_PARID: 25098,
                C_ZQCODE: '350102',
                C_ZQNAME: '鼓楼区',
                isLeaf: false,
              },
              {
                L_ID: 22166,
                L_PARID: 25098,
                C_ZQCODE: '350104',
                C_ZQNAME: '仓山区',
                isLeaf: false,
              },
              {
                L_ID: 25115,
                L_PARID: 25098,
                C_ZQCODE: '350105',
                C_ZQNAME: '马尾区',
                isLeaf: false,
              },
              {
                L_ID: 25120,
                L_PARID: 25098,
                C_ZQCODE: '350111',
                C_ZQNAME: '晋安区',
                isLeaf: false,
              },
              {
                L_ID: 25130,
                L_PARID: 25098,
                C_ZQCODE: '350121',
                C_ZQNAME: '闽侯县',
                isLeaf: false,
              },
              {
                L_ID: 25150,
                L_PARID: 25098,
                C_ZQCODE: '350122',
                C_ZQNAME: '连江县',
                isLeaf: false,
              },
              {
                L_ID: 25174,
                L_PARID: 25098,
                C_ZQCODE: '350123',
                C_ZQNAME: '罗源县',
                isLeaf: false,
              },
              {
                L_ID: 25185,
                L_PARID: 25098,
                C_ZQCODE: '350124',
                C_ZQNAME: '闽清县',
                isLeaf: false,
                child: [
                  {
                    L_ID: 25186,
                    L_PARID: 25185,
                    C_ZQCODE: '350124100',
                    C_ZQNAME: '梅城',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25187,
                    L_PARID: 25185,
                    C_ZQCODE: '350124101',
                    C_ZQNAME: '梅溪',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25188,
                    L_PARID: 25185,
                    C_ZQCODE: '350124102',
                    C_ZQNAME: '白樟',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25189,
                    L_PARID: 25185,
                    C_ZQCODE: '350124103',
                    C_ZQNAME: '金沙',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25190,
                    L_PARID: 25185,
                    C_ZQCODE: '350124104',
                    C_ZQNAME: '白中',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25191,
                    L_PARID: 25185,
                    C_ZQCODE: '350124105',
                    C_ZQNAME: '池园',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25192,
                    L_PARID: 25185,
                    C_ZQCODE: '350124106',
                    C_ZQNAME: '坂东',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25193,
                    L_PARID: 25185,
                    C_ZQCODE: '350124107',
                    C_ZQNAME: '塔庄',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25194,
                    L_PARID: 25185,
                    C_ZQCODE: '350124108',
                    C_ZQNAME: '省璜',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25195,
                    L_PARID: 25185,
                    C_ZQCODE: '350124109',
                    C_ZQNAME: '雄江',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25196,
                    L_PARID: 25185,
                    C_ZQCODE: '350124110',
                    C_ZQNAME: '东桥',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25197,
                    L_PARID: 25185,
                    C_ZQCODE: '350124200',
                    C_ZQNAME: '云龙',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25198,
                    L_PARID: 25185,
                    C_ZQCODE: '350124201',
                    C_ZQNAME: '上莲',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25199,
                    L_PARID: 25185,
                    C_ZQCODE: '350124204',
                    C_ZQNAME: '三溪',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25200,
                    L_PARID: 25185,
                    C_ZQCODE: '350124205',
                    C_ZQNAME: '桔林',
                    isLeaf: true,
                  },
                  {
                    L_ID: 25201,
                    L_PARID: 25185,
                    C_ZQCODE: '350124206',
                    C_ZQNAME: '下祝',
                    isLeaf: true,
                  },
                ],
              },
              {
                L_ID: 25202,
                L_PARID: 25098,
                C_ZQCODE: '350125',
                C_ZQNAME: '永泰县',
                isLeaf: false,
              },
              {
                L_ID: 25224,
                L_PARID: 25098,
                C_ZQCODE: '350181',
                C_ZQNAME: '福清市',
                isLeaf: false,
              },
              {
                L_ID: 25249,
                L_PARID: 25098,
                C_ZQCODE: '350182',
                C_ZQNAME: '长乐市',
                isLeaf: false,
              },
            ],
          },
          {
            L_ID: 25268,
            L_PARID: 25097,
            C_ZQCODE: '3502',
            C_ZQNAME: '厦门市',
            isLeaf: false,
          },
          {
            L_ID: 25323,
            L_PARID: 25097,
            C_ZQCODE: '3503',
            C_ZQNAME: '莆田市',
            isLeaf: false,
          },
          {
            L_ID: 25390,
            L_PARID: 25097,
            C_ZQCODE: '3504',
            C_ZQNAME: '三明市',
            isLeaf: false,
          },
          {
            L_ID: 25540,
            L_PARID: 25097,
            C_ZQCODE: '3505',
            C_ZQNAME: '泉州市',
            isLeaf: false,
          },
          {
            L_ID: 25717,
            L_PARID: 25097,
            C_ZQCODE: '3506',
            C_ZQNAME: '漳州市',
            isLeaf: false,
          },
          {
            L_ID: 25878,
            L_PARID: 25097,
            C_ZQCODE: '3507',
            C_ZQNAME: '南平市',
            isLeaf: false,
          },
          {
            L_ID: 25845,
            L_PARID: 25097,
            C_ZQCODE: '3508',
            C_ZQNAME: '龙岩市',
            isLeaf: false,
          },
          {
            L_ID: 26168,
            L_PARID: 25097,
            C_ZQCODE: '3509',
            C_ZQNAME: '宁德市',
            isLeaf: false,
          },
          {
            L_ID: 26307,
            L_PARID: 25097,
            C_ZQCODE: '3510',
            C_ZQNAME: '平潭综合实验区',
            isLeaf: false,
          },
        ],
      },
      {
        L_ID: 26324,
        L_PARID: 12565,
        C_ZQCODE: '36',
        C_ZQNAME: '江西省',
      },
      {
        L_ID: 28100,
        L_PARID: 12565,
        C_ZQCODE: '37',
        C_ZQNAME: '山东省',
      },
      {
        L_ID: 30091,
        L_PARID: 12565,
        C_ZQCODE: '41',
        C_ZQNAME: '河南省',
      },
      {
        L_ID: 32564,
        L_PARID: 12565,
        C_ZQCODE: '42',
        C_ZQNAME: '湖北省',
      },
      {
        L_ID: 34365,
        L_PARID: 12565,
        C_ZQCODE: '43',
        C_ZQNAME: '湖南省',
      },
      {
        L_ID: 36985,
        L_PARID: 12565,
        C_ZQCODE: '44',
        C_ZQNAME: '广东省',
      },
      {
        L_ID: 39108,
        L_PARID: 12565,
        C_ZQCODE: '45',
        C_ZQNAME: '广西壮族自治区',
      },
      {
        L_ID: 40772,
        L_PARID: 12565,
        C_ZQCODE: '46',
        C_ZQNAME: '海南省',
      },
      {
        L_ID: 41106,
        L_PARID: 12565,
        C_ZQCODE: '50',
        C_ZQNAME: '重庆市',
      },
      {
        L_ID: 41807,
        L_PARID: 12565,
        C_ZQCODE: '51',
        C_ZQNAME: '四川省',
      },
      {
        L_ID: 46543,
        L_PARID: 12565,
        C_ZQCODE: '52',
        C_ZQNAME: '贵州省',
      },
      {
        L_ID: 48238,
        L_PARID: 12565,
        C_ZQCODE: '53',
        C_ZQNAME: '云南省',
      },
      {
        L_ID: 49780,
        L_PARID: 12565,
        C_ZQCODE: '54',
        C_ZQNAME: '西藏自治区',
      },
      {
        L_ID: 50748,
        L_PARID: 12565,
        C_ZQCODE: '61',
        C_ZQNAME: '陕西省',
      },
      {
        L_ID: 52508,
        L_PARID: 12565,
        C_ZQCODE: '62',
        C_ZQNAME: '甘肃省',
      },
      {
        L_ID: 54288,
        L_PARID: 12565,
        C_ZQCODE: '63',
        C_ZQNAME: '青海省',
      },
      {
        L_ID: 54794,
        L_PARID: 12565,
        C_ZQCODE: '64',
        C_ZQNAME: '宁夏回族自治区',
      },
      {
        L_ID: 55173,
        L_PARID: 12565,
        C_ZQCODE: '65',
        C_ZQNAME: '新疆维吾尔自治区',
      },
      {
        L_ID: 56524,
        L_PARID: 12565,
        C_ZQCODE: '91',
        C_ZQNAME: '大兴安岭森工集团',
      },
      {
        L_ID: 56669,
        L_PARID: 12565,
        C_ZQCODE: '92',
        C_ZQNAME: '龙江森工集团',
      },
      {
        L_ID: 61198,
        L_PARID: 12565,
        C_ZQCODE: '93',
        C_ZQNAME: '内蒙森工集团',
      },
      {
        L_ID: 60876,
        L_PARID: 12565,
        C_ZQCODE: '94',
        C_ZQNAME: '吉林森工集团',
      },
      {
        L_ID: 57317,
        L_PARID: 12565,
        C_ZQCODE: '95',
        C_ZQNAME: '新疆生产兵团',
      },
    ],
  },
];
export default datas;
